backend:
  image:
    repository: ntanh23/yas-inventory
    tag: latest

  nameOverride: inventory
  fullnameOverride: inventory
  databaseName: inventory
  databaseSslMode: require
  ingress:
    enabled: false
