username: yasadminuser
password: admin
replicas: 1
postgresqlVersion: "15"
volumeSize: "10Gi"
maxConnections: "200"
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 2Gi
