apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: yas-mtls-policy
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
---
{{- $namespace := .Release.Namespace }}
{{- $backendServices := list "media" "product" "cart" "order" "customer" "inventory" "location" "payment" "promotion" "rating" "recommendation" "search" "tax" "webhook" "storefront-bff" "backoffice-bff" }}
{{- range $dep := .Chart.Dependencies }}
{{- if has $dep.Name $backendServices }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $dep.Name }}-retry-policy
  namespace: {{ $namespace }}
spec:
  hosts:
  - {{ $dep.Name }}
  http:
  - route:
    - destination:
        host: {{ $dep.Name }}
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: 5xx,gateway-error,connect-failure,refused-stream
---
{{- end }}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: yas-mtls-destination
  namespace: {{ $namespace }}
spec:
  host: "*.{{ $namespace }}.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: identity-no-mtls
  namespace: {{ $namespace }}
spec:
  host: identity
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: postgres-no-mtls
  namespace: {{ $namespace }}
spec:
  host: postgres
  trafficPolicy:
    tls:
      mode: DISABLE
---
# Cho phép cả HTTP lẫn mTLS vào Keycloak
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: identity-permissive
  namespace: {{ $namespace }}
spec:
  selector:
    matchLabels:
      app: keycloak
  mtls:
    mode: PERMISSIVE
