backend:
  image:
    repository: ntanh23/yas-search
    tag: latest

  nameOverride: search
  fullnameOverride: search
  databaseName: search
  excludeOutboundPorts: "5432,9200"
  ingress:
    enabled: false
  extraEnvFroms:
    - secretRef:
        name: yas-elasticsearch-credentials-secret
  extraVolumes:
    - name: search-application
      configMap:
        name: search-application-configmap
  extraVolumeMounts:
    - name: search-application
      mountPath: /opt/yas/search
  extraApplicationConfigPaths:
    - /opt/yas/search/search-application.yaml
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
      ephemeral-storage: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
      ephemeral-storage: 512Mi
