# Main values file for yas-staging umbrella chart.

# ── BFF Services ──
storefront-bff:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    fullnameOverride: storefront-bff-staging
    serviceAccount:
      create: true
    image:
      tag: "v1.0.0"        
backoffice-bff:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    fullnameOverride: backoffice-bff-staging
    serviceAccount:
      create: true
    image:
      tag: "v1.0.0"        

# ── UI Services ──
storefront-ui:
  ui:
    image:
      tag: "v1.0.0"

backoffice-ui:
  ui:
    image:
      tag: "v1.0.0"

# ── API Documentation ──
swagger-ui:
  image:
    tag: "v4.16.0"

# ── Backend Services ──
product:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: "v1.0.0"        

media:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: "v1.0.0"

cart:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: "v1.0.0"

order:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: "v1.0.0"

customer:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: "v1.0.0"

inventory:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: "v1.0.0"

location:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: "v1.0.0"

payment:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: "v1.0.0"

promotion:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: "v1.0.0"

rating:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: "v1.0.0"

search:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: "v1.0.0"

tax:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: "v1.0.0"

webhook:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: "v1.0.0"

# ── Infrastructure overrides for Staging (Avoid NodePort conflicts with Dev) ──
database:
  service:
    nodePort: 30107

jaeger:
  service:
    otlpGrpcNodePort: 30117
    otlpHttpNodePort: 30118
