# Main values file for yas-dev umbrella chart.

# ── BFF Services ──
storefront-bff:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    fullnameOverride: storefront-bff
    serviceAccount:
      create: true
    image:
      tag: latest        
backoffice-bff:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    fullnameOverride: backoffice-bff
    serviceAccount:
      create: true
    image:
      tag: latest       

# ── UI Services ──
storefront-ui:
  ui:
    image:
      tag: latest

backoffice-ui:
  ui:
    image:
      tag: latest

# ── API Documentation ──
swagger-ui:
  image:
    tag: "v4.16.0"

# ── Backend Services ──
product:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: latest        

media:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: latest

cart:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: latest

order:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: latest

customer:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: latest

inventory:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: latest

location:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: latest

payment:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: latest

promotion:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: latest

rating:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: latest

search:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: latest

tax:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: latest

webhook:
  backend:
    podAnnotations:
      instrumentation.opentelemetry.io/inject-java: "yas-java"
    image:
      tag: latest
