backend:
  podAnnotations:
    instrumentation.opentelemetry.io/inject-java: "yas-java"

  image:
    repository: ntanh23/yas-product
    tag: latest

  nameOverride: product
  fullnameOverride: product
  databaseName: product
  databaseSslMode: require
  hostAliases:
    - ip: 34.118.226.89
      hostnames:
        - identity.yas.local.com
  ingress:
    enabled: false
  extraVolumes:
    - name: product-application-config
      configMap:
        name: product-application-configmap
  extraVolumeMounts:
    - name: product-application-config
      mountPath: /opt/yas/product
  extraApplicationConfigPaths:
    - /opt/yas/product/product-application.yaml  
