deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  affinity: {}
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  persistence:
    enabled: true
    size: 5Gi

write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  useTestSchema: true

test:
  enabled: false

minio:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false

sidecar:
  rules:
    enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false

gateway:
  enabled: false
