config:
  clients:
    - url: http://loki:3100/loki/api/v1/push
  snippets:
    pipelineStages:
      - cri: {}

defaultVolumes:
  - name: run
    emptyDir: {}
  - name: pods
    hostPath:
      path: /var/log/pods

defaultVolumeMounts:
  - name: run
    mountPath: /run/promtail
  - name: pods
    mountPath: /var/log/pods
    readOnly: true
